---
format: revealjs
editor: source
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```



```{r the_chunk, include = F}
library(gapminder)

gapminder |> 
  filter(year == 2002) |>
  filter(continent == "Americas") |> 
  ggplot() + 
  aes(y = country) + 
  aes(x = gdpPercap) + 
  aes(yend = country,
      xend = 0) +
  geom_segment(color = "red", 
               aes(xend = gdpPercap + 10000)) + 
  geom_segment() + 
  geom_point(size = 8) + 
  aes(color = I("blue")) + 
  aes(size = I(4))
  
```

`r chunq_reveal(chunk_name = "the_chunk", break_type = "auto")`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 120%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

